// Types
export const asyncTypes = Object.freeze({
    CREATE_POSTS_ASYNC: "CREATE_POSTS_ASYNC",
    REMOVE_POSTS_ASYNC: "REMOVE_POSTS_ASYNC",

    // Like
    LIKE_POST_ASYNC:   "LIKE_POST_ASYNC",
    UNLIKE_POST_ASYNC: "UNLIKE_POST_ASYNC",
});
