// Types
export const types = Object.freeze({
    // FETCH
    FETCH_POSTS:         'FETCH_POSTS',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAIL:    'FETCH_POSTS_FAIL',

    // CREATE
    CREATE_POSTS: 'CREATE_POSTS',

    // REMOVE
    REMOVE_POSTS: 'REMOVE_POSTS',

    // LIKE
    LIKE_POST:   'LIKE_POST',
    UNLIKE_POST: 'UNLIKE_POST',
});
