// Types
export const types = Object.freeze({
    EMMIT_ERROR:              "EMMIT_ERROR",
    INITIALIZE:               "INITIALIZE",
    INITIALIZE_SUCCESS:       "INITIALIZE_SUCCESS",
    SET_ONLINE_STATE:         "SET_ONLINE_STATE",
    SET_POSTS_FETCHING_STATE: "SET_POSTS_FETCHING_STATE",
    SET_AUTH_FETCHING_STATE:  "SET_AUTH_FETCHING_STATE",

    // PROFILE
    SET_PROFILE_FETCHING_STATE: "SET_PROFILE_FETCHING_STATE",
    SET_PROFILE_EDITING_STATE:  "SET_PROFILE_EDITING_STATE",
    SET_AVATAR_FETCHING_STATE:  "SET_AVATAR_FETCHING_STATE",
    SET_PASSWORD_EDITING_STATE: "SET_PASSWORD_EDITING_STATE",
});
